name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # her 12 saatte bir çalışır
  workflow_dispatch:  # manuel tetikleme için
  push:
    branches:
      - main  # veya master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Aieyup  # GitHub kullanıcı adınız
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: 'Generate Snake Animation'
          add: 'dist'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
