name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # her 12 saatte bir çalışır
  workflow_dispatch:  # manuel tetikleme için
  push:
    branches:
      - main  # veya master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install canvas dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Aieyup
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
            dist/github-contribution-grid-snake.svg
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: 'Generate Snake Animation'
          add: 'dist'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
